POST http://localhost:3000/file-upload
Content-Type: multipart/form-data; boundary=test-file-upload

--test-file-upload
Content-Disposition: form-data; name="file"; filename="test.txt"

< test.txt
--test-file-upload--

### Upload photo
POST http://localhost:3000/file-upload
Content-Type: multipart/form-data; boundary=image-file-upload

--image-file-upload
Content-Disposition: form-data; name="file"; filename="cat.jpg"

< cat.jpg
--image-file-upload--